script: add check for tmpfs mounted kodi homedir
Some users use tmpfs for /var/lib/kodi/.kodi/temp/ via symlink or bind mount which may cause a delay in kodi writing the log file on a boot due to load time so wait up to 10 sec before crapping out

diff --git a/common/kodi-logger.in b/common/kodi-logger.in
--- a/common/kodi-logger.in
+++ b/common/kodi-logger.in
@@ -20,10 +20,18 @@ check() {
     exit 1
   fi
 
-  if [[ ! -f "$LOG" ]]; then
-    echo " Cannot find $LOG"
-    exit 1
-  fi
+  # some users like to use tmpfs for /var/lib/kodi/.kodi/temp/ via symlink or
+  # bind mount which may cause a delay in the writing the log file on a boot
+  # due to kodi loading so wait up to 10 sec before crapping out
+  for i in {1..10}; do
+    if [[ -f "$LOG" ]]; then
+      return 0
+    else
+      sleep 1s
+    fi
+  done
+
+  [[ $i -eq 10 ]] && echo " Cannot find $LOG";  exit 1
 }
 
 process() {
@@ -62,4 +70,5 @@ fi
 
 rm -f "$TMP"/diff.db "$TMP"/dates.slice "$TMP"/names.slice "$TMP"/rightdates.slice
 
-# vim:set ts=8 sts=2 sw=2 et:
+# vim:set ts=2 sw=2 et:
+
